### PR TITLE
use handouts

### PR DESCRIPTION
**Pull request by lgatto**

### CODE REVIEW

**Comment by lgatto** [comment]
Testing the workflow to generate handouts (see #96)

**Comment by lgatto** [comment]
Adding another commenet to fix check test

**Comment by lgatto** [comment]
@zkamvar - the following PR only changes/adds some purl=TRUE options to code chunks (so that later, I can add handouts). 

The checks fail at the moment, and I'm not sure why, but it could be related to caching that was locked under R 4.2, while now the action uses 4.3. How can I deleted/replace the cache (if that is the issue)?

**Comment by zkamvar** [comment]
I'm running the update cache workflow to see if that can bump your versions: https://github.com/carpentries-incubator/bioc-intro/actions/runs/4930588218. I apologize, the bot wasn't activated for this repo.

Because this is a bioconductor lesson, I'm not terribly familiar about what happens around the boundaries between Bioc releases and CRAN releases. I'm trying to build it on my computer to see what happens and I will report back.

**Comment by zkamvar** [comment]
Let's hope that https://github.com/carpentries-incubator/bioc-intro/pull/98 works 🤞🏼 

After that, I'm going to take a look at [the renv.lock file](https://github.com/carpentries-incubator/bioc-intro/blob/a07d0b2ba73f6f636a2e3f4a274f15410d0f7224/renv/profiles/lesson-requirements/renv.lock) and see if there is anything that I can do to avoid this situation in the future.

**Pull request merged**
